#!/usr/bin/perl
# produire JUSTE des slides style S5 à partir de texte

# usage: ./slidize.pl plan_presentation_orale.txt > slides.html

# voir aussi htmlize.pl pour une génération de doc HTML complet

use 5.010;
use strict;
use warnings;
use open qw(:std :utf8); # this is required to read utf8 with <>

my $line = 0;
my $closeprev = "</ul></div>\n";
my $datestring = localtime();
my $generation_info = "slides generated by '$0 $ARGV[0]' on $datestring";

# slurp the surrounding HTML
my $file = "pres_skel.html";
my $contents = do { local(@ARGV, $/) = $file; <> };
my ($begin, $end) = split /\[GENERATED SLIDES\]/, $contents;

print $begin;

print <<END;
<!-- begin $generation_info -->
END

while (<>) {
    if (!/^\s/) {
        chomp;
        my $closeprevious = $line == 0 ? "" : $closeprev;
        print <<END;
$closeprevious

<div class="slide">
<h1>$_</h1>
<ul>
END
    } else {
        chomp;
        if (/^(\s+)(\w*)$/) {
            print "<li>$2</li>\n";
        } else {
            #print "DEBUG $1<br>\n";
            print "|$_|<br>\n";
        }
    }
    $line++;
    #last if $line > 10;
}

print <<END;
$closeprev
<!-- end $generation_info -->
END

print $end;
